# The URL the site will be built for
base_url = "https://kwon-evan.github.io/"
author = "kwon-evan"
title = "Kwon Evan"
compile_sass = true
build_search_index = true
generate_feed = true
minify_html = true
theme = "papermod"
taxonomies = [
    { name = "tags", feed=true},
]

[markdown]
highlight_code = true

[extra]

[extra.papermod]
title = "Kwon Evan"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["Python", "Rust", "Programming"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = false
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
edit_post_url = "https://github.com/kwon-evan/kwon-evan.github.io/tree/main/"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "https://github.com/kwon-evan", title = "Github", is_external = true }
]

home_title = "Kwon Evan"
home_content = "<b>권헌진</b>(Kwon Heonjin).<br>"
social_icons = [
    { url = "https://github.com/kwon-evan", title = "GitHub", icon = "github" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
